repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.2
    hooks:
      - id: ruff

  - repo: local
    hooks:
      - id: pytest
        name: Run pytest before push
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false # Run pytest on the entire repository
